all:
	touch input.txt output.txt
	g++ -std=c++14 NRZ-I_Encoding.cpp -o NRZ-I_Encoding
	g++ -std=c++14 NRZ-L_Encoding.cpp -o NRZ-L_Encoding	
	g++ -std=c++14 NRZ-I_Decoding.cpp -o NRZ-I_Decoding
	g++ -std=c++14 NRZ-L_Decoding.cpp -o NRZ-L_Decoding

clean:
	rm NRZ-I_Encoding NRZ-L_Encoding NRZ-I_Decoding NRZ-L_Decoding